language: node_js
sudo: false
script:
  - "npm test"
matrix:
  include:
    - node_js: '4'
      before_install: npm -g i npm@2
    - node_js: '4'
      before_install: npm -g i npm@3
    - node_js: 'iojs'
      before_install: npm -g i npm@2
    - node_js: 'iojs'
      before_install: npm -g i npm@3
    - node_js: '0.12'
      before_install: npm -g i npm@2
    - node_js: '0.12'
      before_install: npm -g i npm@3
